'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Game
    Public Property GameID As Integer
    Public Property GameStatus As Integer
    Public Property NumPlayers As Nullable(Of Integer)
    Public Property StartTime As Nullable(Of Date)
    Public Property FinishTime As Nullable(Of Date)
    Public Property Winner As Nullable(Of Integer)

    Public Overridable Property Rounds As ICollection(Of Round) = New HashSet(Of Round)
    Public Overridable Property Players As ICollection(Of Player) = New HashSet(Of Player)

End Class
