'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Hand
    Public Property HandID As Integer
    Public Property RoundID As Integer
    Public Property PlayerID As Integer
    Public Property Card01 As Integer
    Public Property Card02 As Integer
    Public Property Card03 As Integer
    Public Property Card04 As Integer
    Public Property Card05 As Integer
    Public Property Card06 As Integer
    Public Property Card07 As Integer
    Public Property Card08 As Integer
    Public Property Card09 As Integer
    Public Property Card10 As Integer
    Public Property Selection As String
    Public Property Vote As Nullable(Of Integer)

    Public Overridable Property Player As Player
    Public Overridable Property Round As Round

End Class
