'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RoundWinner
    Public Property PlayerID As Integer
    Public Property RoundID As Integer

    Public Overridable Property Player As Player
    Public Overridable Property Round As Round

End Class
